// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/asragi/yasoba-prototype/adapter/ebiten/drawing/adapter"
	adapter2 "github.com/asragi/yasoba-prototype/adapter/ebiten/sequence/adapter"
	"github.com/asragi/yasoba-prototype/battle"
	actor2 "github.com/asragi/yasoba-prototype/battle/actor"
	"github.com/asragi/yasoba-prototype/battle/combination"
	"github.com/asragi/yasoba-prototype/battle/config"
	"github.com/asragi/yasoba-prototype/battle/decision"
	"github.com/asragi/yasoba-prototype/battle/enemy"
	"github.com/asragi/yasoba-prototype/battle/invoke"
	"github.com/asragi/yasoba-prototype/battle/partner"
	"github.com/asragi/yasoba-prototype/battle/setup"
	"github.com/asragi/yasoba-prototype/battle/skill"
	"github.com/asragi/yasoba-prototype/common/character"
	"github.com/asragi/yasoba-prototype/debug"
	"github.com/asragi/yasoba-prototype/frontend"
	"github.com/asragi/yasoba-prototype/scene"
	"github.com/asragi/yasoba-prototype/sequence"
	"github.com/asragi/yasoba-prototype/text"
	"github.com/asragi/yasoba-prototype/toolkit/drawing"
	"github.com/asragi/yasoba-prototype/util"
	"github.com/asragi/yasoba-prototype/view/battle/actor"
	"github.com/asragi/yasoba-prototype/view/battle/damage"
	enemy2 "github.com/asragi/yasoba-prototype/view/battle/enemy"
	"github.com/asragi/yasoba-prototype/view/battle/event"
	"github.com/asragi/yasoba-prototype/view/battle/hp"
	"github.com/asragi/yasoba-prototype/view/battle/window"
	"github.com/asragi/yasoba-prototype/view/common/message"
	"github.com/asragi/yasoba-prototype/view/common/selection"
	transition "github.com/asragi/yasoba-prototype/view/common/transition"
	"github.com/asragi/yasoba-prototype/widget"
	"math/rand"
)

// Injectors from wire.go:

func initializeApp(cfg Config) (*App, error) {
	drawingDrawing := drawing.NewDrawing()
	resourceManager, err := frontend.CreateResourceManager()
	if err != nil {
		return nil, err
	}
	drawTextFunc := adapter.NewDrawTextFunc()
	newTextFunc := widget.CreateNewText(resourceManager, drawTextFunc)
	newWindowFunc := makeWindowFunc(resourceManager, cfg)
	newMessageWindowFunc := message.StandByNewMessageWindow(newTextFunc, newWindowFunc)
	newCursor := makeSelectCursor(resourceManager)
	serveTextDataFunc, err := loadTextServer(cfg)
	if err != nil {
		return nil, err
	}
	newSelectWindowFunc := selection.StandByNewSelectWindow(newCursor, newTextFunc, serveTextDataFunc)
	newBattleSelectWindowFunc := window.StandByNewBattleSelectWindow(newSelectWindowFunc)
	newFaceWindowFunc := makeFaceWindowFactory(resourceManager, newWindowFunc)
	newDisplayDamageFunc := damage.CreateNewDisplayDamage(newTextFunc)
	fontId := _wireFontIdValue
	newBattleHPDisplayFunc := hp.CreateNewBattleHPDisplay(fontId, newTextFunc)
	newBattleParameterDisplayFunc := actor.CreateNewBattleParameterDisplay(newWindowFunc, newBattleHPDisplayFunc)
	newBattleActorDisplayFunc := actor.CreateNewBattleActorDisplay(newFaceWindowFunc, newDisplayDamageFunc, newBattleParameterDisplayFunc)
	newBattleSubActorDisplayFunc := actor.CreateNewBattleSubActorDisplay(newFaceWindowFunc, newDisplayDamageFunc, newBattleParameterDisplayFunc)
	newTransitionViewFunc := makeTransitionView(resourceManager, cfg)
	nameServer := enemy.CreateNameServer()
	serveCharacterFunc := character.CreateCharacterServer()
	serveEnemyData := enemy.CreateEnemyServer()
	inMemoryActorServer := actor2.NewInMemoryActorServer()
	service := makePrepareService(serveCharacterFunc, serveEnemyData, inMemoryActorServer)
	emitRandomFunc := _wireEmitRandomFuncValue
	serveBattleState := makeServeBattleState(inMemoryActorServer)
	newPartnerActionServer := partner.StandByNewPartnerActionServer(emitRandomFunc, serveBattleState)
	partnerActionServer := makePartnerActionServer(newPartnerActionServer)
	initializeBattleFunc := makeInitializeBattle(service, partnerActionServer)
	serveFunc := config.NewServer()
	serveBattleEventSequenceFunc := event.CreateServeBattleEventSequence()
	prepareBattleEventSequenceFunc := event.CreateExecBattleEventSequence(serveTextDataFunc, serveBattleEventSequenceFunc)
	skillToSequenceFunc := _wireSkillToSequenceFuncValue
	getEnemyGraphicsFunc := enemy2.CreateGetEnemyGraphics()
	newBattleEnemyGraphicsFunc := makeBattleEnemyGraphics(resourceManager, getEnemyGraphicsFunc, newDisplayDamageFunc, cfg)
	newBattleEnemyDisplayFunc := enemy2.CreateNewBattleEnemyDisplay(newBattleEnemyGraphicsFunc)
	serveEffectDataFunc := widget.CreateServeEffectData()
	effectManager := widget.NewEffectManager(serveEffectDataFunc, resourceManager)
	serveEnemyViewData := enemy2.NewServeEnemyViewData()
	actorSupplier := makeActorSupplier(inMemoryActorServer)
	processPlayerCommandFunc := battle.CreateProcessPlayerCommand(actorSupplier)
	checkFunc := combination.CreateCheckCombination()
	serveSkillData := skill.NewSkillServer()
	updateActorFunc := makeActorUpdater(inMemoryActorServer)
	skillApplyFunc := skill.CreateSkillApply(serveSkillData, actorSupplier, updateActorFunc, emitRandomFunc)
	decideActionOrderFunc := battle.CreateDecideActionOrder(inMemoryActorServer)
	choiceSkillTargetFunc := decision.CreateChoiceSkillTarget(emitRandomFunc)
	newChoiceRandomActionFunc := decision.StandByCreateRandomAction(emitRandomFunc, serveSkillData, choiceSkillTargetFunc)
	newChoiceActionFunc := decision.CreateNewChoiceAction(newChoiceRandomActionFunc)
	newProcessBattleFunc := makeProcessBattle(actorSupplier, serveBattleState, processPlayerCommandFunc, partnerActionServer, checkFunc, skillApplyFunc, decideActionOrderFunc, newChoiceActionFunc)
	prepareProduceCreateSequence := adapter2.InitializeProduceCreateSequence()
	produceCreateSequence := makeProduceCreateSequence(prepareProduceCreateSequence, serveTextDataFunc)
	produceCheckInvokeSequence := invoke.InitializeProduceCheckInvokeSequence()
	createBattleScene := scene.InitializeCreateBattleScene(newMessageWindowFunc, newSelectWindowFunc, newBattleSelectWindowFunc, newBattleActorDisplayFunc, newBattleSubActorDisplayFunc, newTransitionViewFunc, nameServer, initializeBattleFunc, serveFunc, prepareBattleEventSequenceFunc, skillToSequenceFunc, newBattleEnemyDisplayFunc, effectManager, serveEnemyViewData, actorSupplier, newProcessBattleFunc, produceCreateSequence, produceCheckInvokeSequence)
	createDebugScene := scene.InitializeCreateDebugScene(newSelectWindowFunc)
	debugDebug := debug.CreateDrawParameters(newTextFunc)
	app := buildApp(drawingDrawing, createBattleScene, createDebugScene, debugDebug, cfg)
	return app, nil
}

var (
	_wireFontIdValue              = frontend.MaruMinya
	_wireEmitRandomFuncValue      = util.EmitRandomFunc(rand.Float64)
	_wireSkillToSequenceFuncValue = event.SkillToSequenceFunc(event.ToEventSequenceId)
)

// wire.go:

func loadTextServer(cfg Config) (text.ServeTextDataFunc, error) {
	return text.LoadFromYAML(cfg.TextDataPath)
}

func makeProduceCreateSequence(prepare sequence.PrepareProduceCreateSequence, textServer text.ServeTextDataFunc) sequence.ProduceCreateSequence {
	return prepare(textServer)
}

func makeActorSupplier(server *actor2.InMemoryActorServer) actor2.ActorSupplier {
	return server.Get
}

func makeActorUpdater(server *actor2.InMemoryActorServer) actor2.UpdateActorFunc {
	return server.Upsert
}

func makeServeBattleState(server *actor2.InMemoryActorServer) decision.ServeBattleState {
	return decision.CreateServeBattleState(server)
}

func makePrepareService(
	serveCharacter character.ServeCharacterFunc,
	serveEnemy enemy.ServeEnemyData,
	server *actor2.InMemoryActorServer,
) setup.Service {
	return setup.NewPrepareService(serveCharacter, serveEnemy, server)
}

func makePartnerActionServer(factory partner.NewPartnerActionServer) *partner.PartnerActionServer {
	return factory()
}

func makeInitializeBattle(prepare setup.Service, partnerServer *partner.PartnerActionServer) battle.InitializeBattleFunc {
	return battle.CreateInitializeBattle(prepare, partnerServer.DecidePlan)
}

func makeProcessBattle(
	getActor actor2.ActorSupplier,
	serveBattleState decision.ServeBattleState,
	processCommand battle.ProcessPlayerCommandFunc,
	partnerServer *partner.PartnerActionServer,
	checkCombination combination.CheckFunc,
	skillApply skill.SkillApplyFunc,
	decideActionOrder battle.DecideActionOrderFunc,
	choiceAction decision.NewChoiceActionFunc,
) battle.NewProcessBattleFunc {
	return battle.StandByCreateProcessBattle(
		getActor,
		serveBattleState,
		processCommand,
		partnerServer.GetPlan,
		checkCombination,
		skillApply,
		decideActionOrder,
		choiceAction,
	)
}

func makeWindowFunc(resource *frontend.ResourceManager, cfg Config) widget.NewWindowFunc {
	return widget.CreateNewWindow(resource.GetTexture, cfg.GameWidth, cfg.GameHeight)
}

func makeBattleEnemyGraphics(
	resource frontend.ResourceManagerInterface,
	getEnemyGraphics enemy2.GetEnemyGraphicsFunc,
	newDisplayDamage damage.NewDisplayDamageFunc,
	cfg Config,
) enemy2.NewBattleEnemyGraphicsFunc {
	return enemy2.NewBattleActorGraphics(
		resource,
		getEnemyGraphics,
		newDisplayDamage,
		cfg.GameWidth,
		cfg.GameHeight,
	)
}

func makeTransitionView(resource frontend.ResourceManagerInterface, cfg Config) transition.NewTransitionViewFunc {
	createImage := func(width, height int) transition.OverlayImage {
		img := resource.NewEmptyImage(width, height)
		overlay, ok := img.(transition.OverlayImage)
		if !ok {
			panic("transition: created image does not satisfy overlay interface")
		}
		return overlay
	}
	return transition.CreateNewView(
		cfg.GameWidth,
		cfg.GameHeight,
		drawing.DepthTransition,
		createImage,
	)
}

func makeSelectCursor(resource *frontend.ResourceManager) selection.NewCursor {
	return func(
		relativePosition *drawing.Vector,
		pivot *drawing.Pivot,
		depth drawing.Depth,
	) selection.Cursor {
		return widget.NewImage(
			relativePosition,
			pivot,
			depth,
			resource.GetTexture(frontend.TextureCursor),
		)
	}
}

func makeFaceWindowFactory(resource *frontend.ResourceManager, newWindow widget.NewWindowFunc) actor.NewFaceWindowFunc {
	return actor.StandByNewFaceWindow(resource, newWindow)
}
