// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject

package app

func initializeApp(cfg Config) (*App, error) {
	drawing := provideDrawing()
	battleSceneResult, err := provideBattleSceneResult(cfg)
	if err != nil {
		return nil, err
	}
	debug := provideDebug(battleSceneResult)
	app := buildApp(drawing, battleSceneResult, debug)
	return app, nil
}
